"""add price to perfumes

Revision ID: 591350a26fe4
Revises: 2b8f94266c12
Create Date: 2026-08-01 15:00:02.134805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '591350a26fe4'
down_revision: Union[str, Sequence[str], None] = '2b8f94266c12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfumes', sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perfumes', 'precio')
    # ### end Alembic commands ###
