"""make perfume brand required

Revision ID: 780b88e0a00e
Revises: d57b5c98b8d5
Create Date: 2026-08-20 11:56:35.762928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '780b88e0a00e'
down_revision: Union[str, Sequence[str], None] = 'd57b5c98b8d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('perfumes', 'marca_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('perfumes_marca_id_fkey'), 'perfumes', type_='foreignkey')
    op.create_foreign_key('perfumes_marca_id_fkey', 'perfumes', 'marcas', ['marca_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('perfumes_marca_id_fkey', 'perfumes', type_='foreignkey')
    op.create_foreign_key(op.f('perfumes_marca_id_fkey'), 'perfumes', 'marcas', ['marca_id'], ['id'], ondelete='SET NULL')
    op.alter_column('perfumes', 'marca_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
