"""add_discount_to_perfumes

Revision ID: 89bee674bd17
Revises: fa9a4066d8ab
Create Date: 2026-10-01 12:33:28.930519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89bee674bd17'
down_revision: Union[str, Sequence[str], None] = 'fa9a4066d8ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfumes', sa.Column('descuento', sa.Integer(), nullable=True))
    op.create_check_constraint(constraint_name='ck_perfumes_descuento_valido', table_name='perfumes', condition='descuento is NULL or (descuento > 0 AND descuento < 100)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(constraint_name='ck_perfumes_descuento_valido', table_name='perfumes', type_='check')
    op.drop_column('perfumes', 'descuento')
    # ### end Alembic commands ###
