"""add_pedidos_and_linea_pedidos

Revision ID: 9efcc181d741
Revises: 25f4830c3c7f
Create Date: 2026-09-14 11:20:15.562352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9efcc181d741'
down_revision: Union[str, Sequence[str], None] = '25f4830c3c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lineas_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('perfume_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='ck_linea_pedido_cantidad_positiva'),
    sa.CheckConstraint('precio_unidad > 0', name='ck_linea_pedido_precio_unidad_positiva'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['perfume_id'], ['perfumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lineas_pedido')
    op.drop_table('pedidos')
    # ### end Alembic commands ###
