"""add users table

Revision ID: d57b5c98b8d5
Revises: f8f0ae8f09e1
Create Date: 2026-08-05 18:46:00.865685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd57b5c98b8d5'
down_revision: Union[str, Sequence[str], None] = 'f8f0ae8f09e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('user', 'admin', name='rol_usuario'), server_default='user', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    rol_usuario_enum = postgresql.ENUM(
        "user",
        "admin",
        name="rol_usuario"
    )

    rol_usuario_enum.drop(
        op.get_bind(),
        checkfirst=True
    )
    # ### end Alembic commands ###
