"""make perfume price required

Revision ID: d6df392c2ac4
Revises: 591350a26fe4
Create Date: 2026-08-01 15:43:41.167733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6df392c2ac4'
down_revision: Union[str, Sequence[str], None] = '591350a26fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('perfumes', 'precio',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    
    
    op.create_check_constraint(
        "ck_perfumes_precio_positivo",
        "perfumes",
        "precio > 0"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_perfumes_precio_positivo",
        "perfumes",
        type_="check",
    )
    
    op.alter_column('perfumes', 'precio',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###
