"""add stock to perfumes

Revision ID: f8f0ae8f09e1
Revises: d6df392c2ac4
Create Date: 2026-08-03 12:36:49.261731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8f0ae8f09e1'
down_revision: Union[str, Sequence[str], None] = 'd6df392c2ac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfumes', sa.Column('stock', sa.Integer(), server_default='0', nullable=False))
    
    op.create_check_constraint(
        "ck_perfumes_stock_no_negativo",
        "perfumes",
        "stock >= 0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_perfumes_stock_no_negativo",
        "perfumes",
        type_="check",
    )
    
    op.drop_column('perfumes', 'stock')
    # ### end Alembic commands ###
