"""add_nombre_perfume_to_linea_pedido

Revision ID: fa9a4066d8ab
Revises: 9efcc181d741
Create Date: 2026-09-18 17:49:47.333361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa9a4066d8ab'
down_revision: Union[str, Sequence[str], None] = '9efcc181d741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lineas_pedido', sa.Column('nombre_perfume', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lineas_pedido', 'nombre_perfume')
    # ### end Alembic commands ###
